name: pedants

on:
  workflow_dispatch: null
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  backend:
    name: PHP 7.4 on ubuntu-22.04
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./backend

    env:
      APP_TITLE: Shipyard
      BASE_URL: /
      LOG_LEVEL: OFF
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: shipyard
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
    - uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict --no-check-version

    - name: Get Composer Cache Directory
      id: composer-cache-restore
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Restore Composer Cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.composer-cache-restore.outputs.dir }}
        key: ubuntu-22.04-php7.4-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ubuntu-22.04-php7.4-composer-

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        composer require --dev friendsofphp/php-cs-fixer phpstan/phpstan

    - name: Run phpstan and php-cs-fixer
      run: |
        composer style-check
        vendor/bin/phpstan analyse

  frontend:
    name: Node.js on ubuntu-22.04
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint
